- hosts: raspberry
  tasks:
    - name: Find content in directory
      find:
        path: "/home/pi/testdir/"
        file_type: any 
      register: all_content
    - name: Delete
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ all_content.files }}"
